# Generated by Django 4.1 on 2022-08-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_part_onhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amountTaken', models.BigIntegerField()),
                ('dateTaken', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='workerKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workeKey', to='api.worker'),
        ),
    ]
