# Generated by Django 4.1 on 2022-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_worker_part_workerkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='workerKey',
        ),
        migrations.AddField(
            model_name='part',
            name='workerKey',
            field=models.ManyToManyField(null=True, related_name='workeKey', to='api.worker'),
        ),
    ]
