# Generated by Django 4.1 on 2022-08-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_worker_amounttaken_remove_worker_datetaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='workerKey',
        ),
        migrations.AddField(
            model_name='part',
            name='drawList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.worker'),
        ),
    ]
