# Generated by Django 4.1 on 2022-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_part_workerkey_part_drawlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='drawList',
        ),
        migrations.AddField(
            model_name='part',
            name='drawList',
            field=models.ManyToManyField(to='api.worker'),
        ),
    ]
