# Generated by Django 4.1 on 2022-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_part_drawlist_part_drawlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='amountTaken',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='dateTaken',
            field=models.DateField(null=True),
        ),
    ]
